datasets:
  base-mainnet:
    measurements:
      processing_time:
        reference:
          kind: block_time_api
          urls:
            - http://localhost:3000
            - http://localhost:3001
        target:
          kind: portal_api
          dataset_kind: evm
          url: https://portal.sqd.dev/datasets/base-mainnet
  solana-mainnet:
    measurements:
      processing_time:
        reference:
          kind: block_time_api
          urls:
            - http://localhost:4000
            - http://localhost:4001
            - http://localhost:4002
        target:
          kind: portal_api
          dataset_kind: solana
          url: https://portal.sqd.dev/datasets/solana-mainnet